"""
Train a Logistic Regression model on the cleaned SafeSched deadlock dataset.

This script is intentionally practical and straightforward:
1. Read the cleaned dataset generated by preprocess_dead_data.py.
2. Split data into train/test sets with stratification.
3. Build a preprocessing + Logistic Regression pipeline.
4. Train, evaluate, and save the model and metrics.
"""

# Standard library imports for command-line arguments, JSON output, and file paths.
import ast
import argparse
import json
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# Third-party imports for model persistence and data/model handling.
import joblib
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import GroupShuffleSplit, train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler


ALLOCATION_COLUMN_CANDIDATES = [
    "allocation_matrix",
    "allocation",
    "allocation_state",
]
MAX_COLUMN_CANDIDATES = [
    "max_matrix",
    "max",
    "max_demand_matrix",
]
AVAILABLE_COLUMN_CANDIDATES = [
    "available",
    "available_vector",
    "available_resources",
]

MATRIX_MODEL_FEATURE_COLUMNS = [
    "num_processes",
    "num_resources",
    "total_resources",
    "distributed",
    "dynamic_join_leave",
    "total_allocation",
    "total_max",
    "total_need",
    "sum_available",
    "unmet_need_processes",
    "feasible_processes_now",
    "unmet_demand_vs_supply",
    "resource_utilization_ratio",
]


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments to control data paths and training settings."""
    parser = argparse.ArgumentParser(
        description="Train Logistic Regression on cleaned deadlock dataset."
    )

    # Input cleaned dataset path.
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("datasets/dead_data_preprocessed.csv"),
        help="Path to cleaned CSV dataset.",
    )

    # Target column used for binary classification.
    parser.add_argument(
        "--target",
        type=str,
        default="deadlock",
        help="Name of binary target column.",
    )

    # Fraction of dataset reserved for test evaluation.
    parser.add_argument(
        "--test-size",
        type=float,
        default=0.20,
        help="Test split ratio (e.g., 0.20 means 20%% test set).",
    )

    # Random seed to keep train/test split and model behavior reproducible.
    parser.add_argument(
        "--random-state",
        type=int,
        default=42,
        help="Random seed for reproducibility.",
    )

    # Split mode controls the evaluation split strategy.
    parser.add_argument(
        "--split-mode",
        type=str,
        default="group_shuffle",
        choices=["group_shuffle", "random"],
        help=(
            "Train/test split strategy: "
            "'group_shuffle' uses GroupShuffleSplit with feature-hash groups (recommended); "
            "'random' keeps old stratified row split for comparison only."
        ),
    )

    # Training mode controls whether to use input CSV or matrix-synthetic training data.
    parser.add_argument(
        "--train-mode",
        type=str,
        default="dataset",
        choices=["dataset", "matrix_synthetic"],
        help=(
            "Training mode: "
            "'dataset' trains from --input CSV; "
            "'matrix_synthetic' generates matrix states, labels them via safe-sequence logic, "
            "and trains on matrix-derived features aligned with backend inference."
        ),
    )

    parser.add_argument(
        "--synthetic-samples",
        type=int,
        default=12000,
        help="Number of synthetic matrix states to generate in matrix_synthetic mode.",
    )

    parser.add_argument(
        "--synthetic-min-processes",
        type=int,
        default=3,
        help="Minimum process count for synthetic matrix generation.",
    )

    parser.add_argument(
        "--synthetic-max-processes",
        type=int,
        default=12,
        help="Maximum process count for synthetic matrix generation.",
    )

    parser.add_argument(
        "--synthetic-min-resources",
        type=int,
        default=2,
        help="Minimum resource type count for synthetic matrix generation.",
    )

    parser.add_argument(
        "--synthetic-max-resources",
        type=int,
        default=7,
        help="Maximum resource type count for synthetic matrix generation.",
    )

    # Name of column that carries feature-hash group id from preprocessing.
    parser.add_argument(
        "--group-column",
        type=str,
        default="feature_hash",
        help="Grouping column used for GroupShuffleSplit.",
    )

    # Output model artifact path.
    parser.add_argument(
        "--model-out",
        type=Path,
        default=Path("models/logistic_regression_deadlock.joblib"),
        help="Path to save trained model artifact.",
    )

    # Output metrics report path.
    parser.add_argument(
        "--metrics-out",
        type=Path,
        default=Path("models/logistic_regression_metrics.json"),
        help="Path to save metrics JSON.",
    )

    return parser.parse_args()


def load_dataset(
    input_path: Path,
    target_col: str,
    group_col: str,
) -> Tuple[pd.DataFrame, pd.Series, bool]:
    """Load cleaned dataset and return X, y, and whether group column exists."""
    # Validate that input file exists before reading.
    if not input_path.exists():
        raise FileNotFoundError(f"Input dataset not found: {input_path}")

    # Read cleaned CSV file.
    df = pd.read_csv(input_path)

    # Validate target presence.
    if target_col not in df.columns:
        raise ValueError(f"Target column '{target_col}' not found in dataset.")

    # Separate features and target.
    x_df = df.drop(columns=[target_col]).copy()
    y_series = df[target_col].astype(int)

    # Track whether preprocessing already provided explicit grouping key.
    group_from_column = group_col in x_df.columns

    return x_df, y_series, group_from_column


def _first_existing_column(x_df: pd.DataFrame, candidates: List[str]) -> Optional[str]:
    """Return first candidate column that exists in DataFrame, else None."""
    for column_name in candidates:
        if column_name in x_df.columns:
            return column_name
    return None


def _parse_array_like(value):
    """Parse list-like objects safely from Python/JSON literals."""
    if isinstance(value, (list, tuple, np.ndarray)):
        return value

    if pd.isna(value):
        return None

    if isinstance(value, str):
        text = value.strip()
        if not text:
            return None

        for parser in (json.loads, ast.literal_eval):
            try:
                return parser(text)
            except (json.JSONDecodeError, ValueError, SyntaxError, TypeError):
                continue

    return None


def _parse_matrix(value) -> Optional[np.ndarray]:
    """Parse a 2D numeric matrix from arbitrary row value."""
    parsed = _parse_array_like(value)
    if parsed is None:
        return None

    try:
        matrix = np.asarray(parsed, dtype=float)
    except (TypeError, ValueError):
        return None

    if matrix.ndim != 2:
        return None

    return matrix


def _parse_vector(value) -> Optional[np.ndarray]:
    """Parse a 1D numeric vector from arbitrary row value."""
    parsed = _parse_array_like(value)
    if parsed is None:
        return None

    try:
        vector = np.asarray(parsed, dtype=float)
    except (TypeError, ValueError):
        return None

    if vector.ndim == 2 and 1 in vector.shape:
        vector = vector.reshape(-1)

    if vector.ndim != 1:
        return None

    return vector


def add_feasibility_features(
    x_df: pd.DataFrame,
) -> Tuple[pd.DataFrame, pd.Series, Dict[str, object]]:
    """
    Add deadlock-feasibility-aware features derived from matrices.

    New features:
    - feasible_processes_now: number of processes with NEED <= available.
    - unmet_demand_vs_supply: max(total NEED - total available, 0).
    - potentially_safe: 1 if any process can proceed now, else 0.

    Also returns logical deadlock rule for diagnostics:
    logical_deadlock_rule = 1 if no process can proceed now, else 0.
    """
    x_out = x_df.copy()

    allocation_col = _first_existing_column(x_out, ALLOCATION_COLUMN_CANDIDATES)
    max_col = _first_existing_column(x_out, MAX_COLUMN_CANDIDATES)
    available_col = _first_existing_column(x_out, AVAILABLE_COLUMN_CANDIDATES)

    logical_deadlock_rule = pd.Series(np.nan, index=x_out.index, dtype="float64")

    if not allocation_col or not max_col or not available_col:
        return x_out, logical_deadlock_rule, {
            "enabled": False,
            "reason": "Required matrix/vector columns were not found in input features.",
            "allocation_column": allocation_col,
            "max_column": max_col,
            "available_column": available_col,
        }

    feasible_processes_now = pd.Series(np.nan, index=x_out.index, dtype="float64")
    unmet_demand_vs_supply = pd.Series(np.nan, index=x_out.index, dtype="float64")
    potentially_safe = pd.Series(np.nan, index=x_out.index, dtype="float64")

    valid_rows = 0
    invalid_rows = 0

    for row_index, row in x_out.iterrows():
        allocation_matrix = _parse_matrix(row[allocation_col])
        max_matrix = _parse_matrix(row[max_col])
        available_vector = _parse_vector(row[available_col])

        if allocation_matrix is None or max_matrix is None or available_vector is None:
            invalid_rows += 1
            continue

        if allocation_matrix.shape != max_matrix.shape:
            invalid_rows += 1
            continue

        n_resources = allocation_matrix.shape[1]
        if available_vector.shape[0] != n_resources:
            invalid_rows += 1
            continue

        if (
            np.any(allocation_matrix < 0)
            or np.any(max_matrix < 0)
            or np.any(available_vector < 0)
            or np.any(allocation_matrix > max_matrix)
        ):
            invalid_rows += 1
            continue

        need_matrix = max_matrix - allocation_matrix
        can_proceed_mask = np.all(need_matrix <= available_vector, axis=1)
        proceed_count = int(np.sum(can_proceed_mask))

        total_need = float(np.sum(need_matrix))
        total_available = float(np.sum(available_vector))
        unmet_minus_supply = float(max(total_need - total_available, 0.0))

        feasible_processes_now.loc[row_index] = float(proceed_count)
        unmet_demand_vs_supply.loc[row_index] = unmet_minus_supply
        potentially_safe.loc[row_index] = float(proceed_count > 0)
        logical_deadlock_rule.loc[row_index] = float(proceed_count == 0)
        valid_rows += 1

    x_out["feasible_processes_now"] = feasible_processes_now
    x_out["unmet_demand_vs_supply"] = unmet_demand_vs_supply
    x_out["potentially_safe"] = potentially_safe

    return x_out, logical_deadlock_rule, {
        "enabled": True,
        "allocation_column": allocation_col,
        "max_column": max_col,
        "available_column": available_col,
        "valid_rows": int(valid_rows),
        "invalid_rows": int(invalid_rows),
        "coverage_ratio": float(valid_rows / len(x_out)) if len(x_out) else 0.0,
        "features_added": [
            "feasible_processes_now",
            "unmet_demand_vs_supply",
            "potentially_safe",
        ],
    }


def _deadlock_label_from_matrices(
    allocation_matrix: np.ndarray,
    max_matrix: np.ndarray,
    available_vector: np.ndarray,
) -> int:
    """Return 1 if matrix state is deadlocked, else 0 (safe-sequence style)."""
    n_proc, n_res = allocation_matrix.shape
    need_matrix = max_matrix - allocation_matrix

    work = available_vector.astype(float).copy()
    finish = [bool(np.all(allocation_matrix[i] == 0)) for i in range(n_proc)]

    progressed = True
    while progressed:
        progressed = False
        for i in range(n_proc):
            if finish[i]:
                continue
            if np.all(need_matrix[i] <= work):
                work = work + allocation_matrix[i]
                finish[i] = True
                progressed = True

    return int(any(not done for done in finish))


def _engineer_matrix_features(
    allocation_matrix: np.ndarray,
    max_matrix: np.ndarray,
    available_vector: np.ndarray,
) -> Dict[str, float]:
    """Build the exact feature set expected by backend matrix inference."""
    n_proc, n_res = allocation_matrix.shape
    need_matrix = max_matrix - allocation_matrix

    total_allocation = float(np.sum(allocation_matrix))
    total_max = float(np.sum(max_matrix))
    total_need = float(np.sum(need_matrix))
    sum_available = float(np.sum(available_vector))

    feasible_processes_now = int(np.sum(np.all(need_matrix <= available_vector, axis=1)))
    unmet_need_processes = int(np.sum(np.any(need_matrix > available_vector, axis=1)))
    unmet_demand_vs_supply = float(max(total_need - sum_available, 0.0))

    denom = total_allocation + sum_available
    resource_utilization_ratio = float(total_allocation / denom) if denom > 0 else 0.0

    return {
        "num_processes": float(n_proc),
        "num_resources": float(n_res),
        "total_resources": float(total_allocation + sum_available),
        "distributed": 0.0,
        "dynamic_join_leave": 0.0,
        "total_allocation": total_allocation,
        "total_max": total_max,
        "total_need": total_need,
        "sum_available": sum_available,
        "unmet_need_processes": float(unmet_need_processes),
        "feasible_processes_now": float(feasible_processes_now),
        "unmet_demand_vs_supply": unmet_demand_vs_supply,
        "resource_utilization_ratio": resource_utilization_ratio,
    }


def generate_matrix_synthetic_dataset(
    n_samples: int,
    random_state: int,
    min_processes: int,
    max_processes: int,
    min_resources: int,
    max_resources: int,
) -> Tuple[pd.DataFrame, pd.Series, Dict[str, object]]:
    """Generate matrix states and labels so model can learn feasibility behavior."""
    if n_samples <= 0:
        raise ValueError("synthetic sample count must be positive")

    rng = np.random.default_rng(seed=random_state)
    feature_rows: List[Dict[str, float]] = []
    labels: List[int] = []

    max_attempts = max(n_samples * 15, 1000)
    attempts = 0

    while len(feature_rows) < n_samples and attempts < max_attempts:
        attempts += 1

        n_proc = int(rng.integers(min_processes, max_processes + 1))
        n_res = int(rng.integers(min_resources, max_resources + 1))

        max_matrix = rng.integers(0, 8, size=(n_proc, n_res)).astype(float)
        allocation_matrix = np.zeros((n_proc, n_res), dtype=float)

        # Keep allocation <= max per cell.
        for i in range(n_proc):
            for j in range(n_res):
                cap = int(max_matrix[i, j])
                allocation_matrix[i, j] = float(rng.integers(0, cap + 1)) if cap > 0 else 0.0

        # Bias availability low enough often to produce blocked/deadlock states.
        available_vector = rng.integers(0, 4, size=n_res).astype(float)

        features = _engineer_matrix_features(
            allocation_matrix=allocation_matrix,
            max_matrix=max_matrix,
            available_vector=available_vector,
        )
        label = _deadlock_label_from_matrices(
            allocation_matrix=allocation_matrix,
            max_matrix=max_matrix,
            available_vector=available_vector,
        )

        feature_rows.append(features)
        labels.append(label)

    if len(feature_rows) < n_samples:
        raise RuntimeError(
            f"Unable to generate requested synthetic samples. generated={len(feature_rows)}, requested={n_samples}."
        )

    x_df = pd.DataFrame(feature_rows)
    x_df = x_df[MATRIX_MODEL_FEATURE_COLUMNS].copy()
    y_series = pd.Series(labels, name="deadlock").astype(int)

    # Moderate rebalance to avoid collapse if one class dominates.
    class_counts = y_series.value_counts().to_dict()
    if len(class_counts) == 2:
        majority_class = int(max(class_counts, key=class_counts.get))
        minority_class = int(min(class_counts, key=class_counts.get))
        majority_idx = y_series[y_series == majority_class].index
        minority_idx = y_series[y_series == minority_class].index

        keep_majority = int(min(len(majority_idx), max(len(minority_idx) * 2, 1)))
        keep_idx = np.concatenate(
            [
                rng.choice(majority_idx.to_numpy(), size=keep_majority, replace=False),
                minority_idx.to_numpy(),
            ]
        )
        rng.shuffle(keep_idx)

        x_df = x_df.loc[keep_idx].reset_index(drop=True)
        y_series = y_series.loc[keep_idx].reset_index(drop=True)

    info = {
        "mode": "matrix_synthetic",
        "requested_samples": int(n_samples),
        "generated_samples": int(len(y_series)),
        "attempts": int(attempts),
        "class_distribution": y_series.value_counts().sort_index().astype(int).to_dict(),
        "feature_columns": MATRIX_MODEL_FEATURE_COLUMNS,
    }
    return x_df, y_series, info


def summarize_class_distribution(y_series: pd.Series) -> Dict[str, Dict[str, float]]:
    """Return class counts and percentages for transparent split diagnostics."""
    total = len(y_series)
    counts = y_series.value_counts().sort_index()

    summary: Dict[str, Dict[str, float]] = {}
    for class_value, count in counts.items():
        summary[str(int(class_value))] = {
            "count": int(count),
            "pct": float(round((count / total) * 100.0, 4)) if total > 0 else 0.0,
        }
    return summary


def split_feature_types(x_df: pd.DataFrame) -> Tuple[List[str], List[str]]:
    """Split features into numeric and categorical groups for preprocessing."""
    # Numeric columns can be scaled for better logistic optimization.
    numeric_cols = [
        col for col in x_df.columns if pd.api.types.is_numeric_dtype(x_df[col])
    ]

    # Remaining columns are treated as categorical/text.
    categorical_cols = [col for col in x_df.columns if col not in numeric_cols]

    return numeric_cols, categorical_cols


def build_training_pipeline(x_df: pd.DataFrame, random_state: int) -> Pipeline:
    """Create a full preprocessing + Logistic Regression training pipeline."""
    # Detect feature types to apply proper preprocessing.
    numeric_cols, categorical_cols = split_feature_types(x_df)

    # Numeric preprocessing: median imputation + standard scaling.
    numeric_preprocess = Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
        ]
    )

    # Categorical preprocessing: most-frequent imputation + one-hot encoding.
    categorical_preprocess = Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
        ]
    )

    # Combine both preprocessors into one transformer.
    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_preprocess, numeric_cols),
            ("cat", categorical_preprocess, categorical_cols),
        ],
        remainder="drop",
    )

    # Logistic Regression model with balanced class weighting for robustness.
    classifier = LogisticRegression(
        max_iter=5000,
        class_weight="balanced",
        random_state=random_state,
    )

    # End-to-end pipeline that handles preprocessing and model training together.
    pipeline = Pipeline(
        steps=[
            ("preprocess", preprocessor),
            ("model", classifier),
        ]
    )

    return pipeline


def build_pattern_keys(x_df: pd.DataFrame) -> pd.Series:
    """
    Build one stable string key per row from all feature columns.

    Rows with identical feature vectors will have identical keys.
    This is used for leakage diagnostics and pattern-holdout splitting.
    """
    return x_df.astype(str).agg("||".join, axis=1)


def compute_leakage_diagnostics(
    x_df: pd.DataFrame,
    y_series: pd.Series,
    train_groups: pd.Series,
    test_groups: pd.Series,
) -> Dict:
    """
    Compute leakage-oriented diagnostics for the current train/test split.

    Reported items include:
    - unique feature pattern count
    - conflicting labels per identical pattern
    - overlap of test patterns with train patterns
    - class-wise count of unique patterns
    """
    # Build pattern keys for full dataset for global diagnostics.
    full_pattern_key = build_pattern_keys(x_df)

    # Aggregate full-dataset pattern behavior.
    pattern_stats = (
        pd.DataFrame({"pattern": full_pattern_key, "target": y_series})
        .groupby("pattern", dropna=False)["target"]
        .agg(["count", "nunique", "mean"])
        .reset_index()
    )

    unique_patterns = int(len(pattern_stats))
    conflicting_patterns = int((pattern_stats["nunique"] > 1).sum())
    max_pattern_frequency = int(pattern_stats["count"].max()) if unique_patterns > 0 else 0
    pattern_to_row_ratio = float(unique_patterns / len(x_df)) if len(x_df) else 0.0

    # Count how many unique patterns map to each class label.
    pattern_stats["class_label"] = pattern_stats["mean"].round().astype(int)
    patterns_per_class = (
        pattern_stats["class_label"].value_counts().sort_index().astype(int).to_dict()
    )

    # Compute group overlap from test into train.
    train_group_set = set(train_groups.astype(str).tolist())
    test_group_values = test_groups.astype(str).tolist()
    overlap_rows = int(sum(key in train_group_set for key in test_group_values))
    overlap_ratio = float(overlap_rows / len(test_group_values)) if len(test_group_values) else 0.0

    # Build red-flag list for direct visibility in logs and metrics file.
    red_flags: List[str] = []
    if pattern_to_row_ratio < 0.30:
        red_flags.append(
            "Low unique-pattern ratio: dataset has many repeated feature vectors."
        )
    if conflicting_patterns == 0:
        red_flags.append(
            "No label conflicts per identical feature pattern; mapping may be deterministic."
        )
    if overlap_ratio > 0.05:
        red_flags.append(
            "Train/test group overlap is above 5%; leakage risk is high."
        )

    return {
        "unique_feature_patterns": unique_patterns,
        "conflicting_patterns": conflicting_patterns,
        "max_pattern_frequency": max_pattern_frequency,
        "pattern_to_row_ratio": pattern_to_row_ratio,
        "patterns_per_class": patterns_per_class,
        "test_pattern_overlap_rows": overlap_rows,
        "test_pattern_overlap_ratio": overlap_ratio,
        "red_flags": red_flags,
    }


def split_dataset(
    x_df: pd.DataFrame,
    y_series: pd.Series,
    groups: pd.Series,
    test_size: float,
    random_state: int,
    split_mode: str,
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.Series, pd.Series, Dict]:
    """
    Split dataset according to selected strategy and return split diagnostics.

    Modes:
    - group_shuffle: GroupShuffleSplit by feature-hash groups (recommended).
    - random: stratified shuffled row-level split (baseline only).
    """
    if split_mode == "random":
        # Standard split for baseline training; shuffle is explicit for clarity.
        x_train, x_test, y_train, y_test = train_test_split(
            x_df,
            y_series,
            test_size=test_size,
            random_state=random_state,
            stratify=y_series,
            shuffle=True,
        )

        # Groups for leakage diagnostics in random mode are derived from provided grouping key.
        group_train = groups.loc[x_train.index]
        group_test = groups.loc[x_test.index]
        return x_train, x_test, y_train, y_test, {
            "split_mode": "random",
            "group_train": group_train,
            "group_test": group_test,
            "warnings": [
                "Random split selected: this can overestimate metrics when duplicate patterns exist."
            ],
        }

    # Group-aware split keeps identical feature hashes entirely in one side.
    max_attempts = 200
    splitter = GroupShuffleSplit(
        n_splits=max_attempts,
        test_size=test_size,
        random_state=random_state,
    )

    selected_train_idx = None
    selected_test_idx = None
    selected_attempt = 0
    selected_balance_score = float("inf")
    warnings: List[str] = []

    # Reference positive-class ratio from full dataset.
    full_positive_ratio = float(y_series.mean())

    # Try multiple group splits and choose the most class-balanced valid split.
    for attempt_idx, (train_idx, test_idx) in enumerate(splitter.split(x_df, y_series, groups=groups), start=1):
        y_train_candidate = y_series.iloc[train_idx]
        y_test_candidate = y_series.iloc[test_idx]

        # Keep the first split as fallback.
        if selected_train_idx is None:
            selected_train_idx = train_idx
            selected_test_idx = test_idx
            selected_attempt = attempt_idx

        # Score only candidates that contain both classes in train and test.
        if y_train_candidate.nunique() == 2 and y_test_candidate.nunique() == 2:
            train_pos_ratio = float(y_train_candidate.mean())
            test_pos_ratio = float(y_test_candidate.mean())

            # Lower score is better (closer to full-data class ratio on both sets).
            balance_score = abs(train_pos_ratio - full_positive_ratio) + abs(test_pos_ratio - full_positive_ratio)

            if balance_score < selected_balance_score:
                selected_balance_score = balance_score
                selected_train_idx = train_idx
                selected_test_idx = test_idx
                selected_attempt = attempt_idx

    # Build selected split.
    x_train = x_df.iloc[selected_train_idx].copy()
    x_test = x_df.iloc[selected_test_idx].copy()
    y_train = y_series.iloc[selected_train_idx].copy()
    y_test = y_series.iloc[selected_test_idx].copy()
    group_train = groups.iloc[selected_train_idx].copy()
    group_test = groups.iloc[selected_test_idx].copy()

    # Warn when split has a single class on one side (can happen with very few positive groups).
    if y_train.nunique() < 2 or y_test.nunique() < 2:
        warnings.append(
            "Could not find a group split with both classes in train/test within search budget; metrics may be unstable."
        )
    else:
        # Still warn when split remains class-skewed due class concentration in few groups.
        train_pos_ratio = float(y_train.mean())
        test_pos_ratio = float(y_test.mean())
        if abs(test_pos_ratio - full_positive_ratio) > 0.20:
            warnings.append(
                "Group-safe split remains class-skewed because class is concentrated in very few unique groups."
            )

    return x_train, x_test, y_train, y_test, {
        "split_mode": "group_shuffle",
        "group_train": group_train,
        "group_test": group_test,
        "attempt_used": selected_attempt,
        "attempt_budget": max_attempts,
        "full_positive_ratio": full_positive_ratio,
        "train_positive_ratio": float(y_train.mean()) if len(y_train) else None,
        "test_positive_ratio": float(y_test.mean()) if len(y_test) else None,
        "balance_score": None if selected_balance_score == float("inf") else selected_balance_score,
        "warnings": warnings,
    }


def _build_behavior_check_rows(feature_columns: List[str]) -> Dict[str, Dict[str, float]]:
    """Build two canonical sanity-check rows for deadlock/safe behavior."""
    deadlock_case = {col: 0.0 for col in feature_columns}
    safe_case = {col: 0.0 for col in feature_columns}

    deadlock_updates = {
        "num_processes": 6.0,
        "num_resources": 3.0,
        "distributed": 0.0,
        "dynamic_join_leave": 0.0,
        "total_allocation": 12.0,
        "total_max": 30.0,
        "total_need": 18.0,
        "total_available": 0.0,
        "num_executable_processes": 0.0,
        "blocked_processes": 6.0,
        "fraction_blocked": 1.0,
        "utilization_ratio": 1.0,
        "need_to_available_ratio": 18.0,
    }

    safe_updates = {
        "num_processes": 6.0,
        "num_resources": 3.0,
        "distributed": 0.0,
        "dynamic_join_leave": 0.0,
        "total_allocation": 6.0,
        "total_max": 10.0,
        "total_need": 4.0,
        "total_available": 10.0,
        "num_executable_processes": 4.0,
        "blocked_processes": 2.0,
        "fraction_blocked": (2.0 / 6.0),
        "utilization_ratio": (6.0 / 16.0),
        "need_to_available_ratio": 0.4,
    }

    # Compatibility for older/alternate feature sets.
    deadlock_updates["total_resources"] = (
        deadlock_updates["total_allocation"] + deadlock_updates["total_available"]
    )
    safe_updates["total_resources"] = (
        safe_updates["total_allocation"] + safe_updates["total_available"]
    )
    deadlock_updates["sum_available"] = deadlock_updates["total_available"]
    safe_updates["sum_available"] = safe_updates["total_available"]
    deadlock_updates["unmet_need_processes"] = deadlock_updates["blocked_processes"]
    safe_updates["unmet_need_processes"] = safe_updates["blocked_processes"]
    deadlock_updates["feasible_processes_now"] = deadlock_updates["num_executable_processes"]
    safe_updates["feasible_processes_now"] = safe_updates["num_executable_processes"]
    deadlock_updates["unmet_demand_vs_supply"] = max(
        deadlock_updates["total_need"] - deadlock_updates["total_available"],
        0.0,
    )
    safe_updates["unmet_demand_vs_supply"] = max(
        safe_updates["total_need"] - safe_updates["total_available"],
        0.0,
    )
    deadlock_updates["resource_utilization_ratio"] = deadlock_updates["utilization_ratio"]
    safe_updates["resource_utilization_ratio"] = safe_updates["utilization_ratio"]

    for key, value in deadlock_updates.items():
        if key in deadlock_case:
            deadlock_case[key] = float(value)
    for key, value in safe_updates.items():
        if key in safe_case:
            safe_case[key] = float(value)

    return {
        "deadlock_case": deadlock_case,
        "safe_case": safe_case,
    }


def _behavior_case_probabilities(model: Pipeline, feature_columns: List[str]) -> Dict[str, float]:
    """Compute deadlock probability for canonical deadlock/safe sanity cases."""
    case_rows = _build_behavior_check_rows(feature_columns)

    deadlock_df = pd.DataFrame([case_rows["deadlock_case"]], columns=feature_columns)
    safe_df = pd.DataFrame([case_rows["safe_case"]], columns=feature_columns)

    if hasattr(model, "predict_proba"):
        deadlock_prob = float(model.predict_proba(deadlock_df)[0][1])
        safe_prob = float(model.predict_proba(safe_df)[0][1])
    else:
        deadlock_prob = float(model.predict(deadlock_df)[0])
        safe_prob = float(model.predict(safe_df)[0])

    return {
        "deadlock_case": deadlock_prob,
        "safe_case": safe_prob,
    }


def _build_behavior_check_report(
    deadlock_case_prob: float,
    safe_case_prob: float,
    threshold: float,
) -> Dict[str, object]:
    """Construct behavior-check report and mismatch messages for logging."""
    deadlock_pred = int(deadlock_case_prob >= threshold)
    safe_pred = int(safe_case_prob >= threshold)

    mismatches: List[str] = []
    if deadlock_pred != 1:
        mismatches.append(
            "Case 1 mismatch: no process can proceed but model predicted deadlock=0"
        )
    if safe_pred != 0:
        mismatches.append(
            "Case 2 mismatch: at least one process can proceed but model predicted deadlock=1"
        )

    return {
        "threshold_used": float(threshold),
        "deadlock_case": {
            "expected_deadlock": 1,
            "prob_deadlock": float(deadlock_case_prob),
            "predicted_deadlock": int(deadlock_pred),
        },
        "safe_case": {
            "expected_deadlock": 0,
            "prob_deadlock": float(safe_case_prob),
            "predicted_deadlock": int(safe_pred),
        },
        "passes_all": len(mismatches) == 0,
        "mismatches": mismatches,
    }


def evaluate_model(
    model: Pipeline,
    x_test: pd.DataFrame,
    y_test: pd.Series,
    logical_deadlock_rule: Optional[pd.Series] = None,
) -> Dict:
    """Compute standard binary classification metrics on the test split."""
    # Probabilities are used for threshold-independent metrics.
    y_prob = model.predict_proba(x_test)[:, 1]

    # Tune classification threshold to maximize F1 (instead of using default 0.50 blindly).
    threshold_values = [round(float(t), 2) for t in np.arange(0.01, 0.51, 0.01)]
    threshold_results: List[Dict[str, float]] = []
    behavior_probs = _behavior_case_probabilities(model, x_test.columns.tolist())

    for threshold in threshold_values:
        y_pred_threshold = (y_prob >= threshold).astype(int)
        deadlock_case_pass = behavior_probs["deadlock_case"] >= threshold
        safe_case_pass = behavior_probs["safe_case"] < threshold
        passes_behavior_checks = bool(deadlock_case_pass and safe_case_pass)

        threshold_results.append(
            {
                "threshold": float(threshold),
                "accuracy": float(accuracy_score(y_test, y_pred_threshold)),
                "precision": float(precision_score(y_test, y_pred_threshold, zero_division=0)),
                "recall": float(recall_score(y_test, y_pred_threshold, zero_division=0)),
                "f1": float(f1_score(y_test, y_pred_threshold, zero_division=0)),
                "passes_behavior_checks": passes_behavior_checks,
                "passes_deadlock_case": bool(deadlock_case_pass),
                "passes_safe_case": bool(safe_case_pass),
            }
        )

    # Pick threshold prioritizing behavior checks, then standard quality metrics.
    best_threshold_result = max(
        threshold_results,
        key=lambda row: (
            int(row["passes_behavior_checks"]),
            row["f1"],
            row["recall"],
            row["precision"],
            -row["threshold"],
        ),
    )
    best_threshold = float(best_threshold_result["threshold"])

    # Final class predictions use tuned threshold.
    y_pred = (y_prob >= best_threshold).astype(int)

    # Core evaluation metrics.
    # Some metrics require both classes in y_test; handle edge cases safely.
    try:
        roc_auc = float(roc_auc_score(y_test, y_prob))
    except ValueError:
        roc_auc = None

    try:
        avg_precision = float(average_precision_score(y_test, y_prob))
    except ValueError:
        avg_precision = None

    metrics = {
        "best_threshold": best_threshold,
        "accuracy": float(accuracy_score(y_test, y_pred)),
        "precision": float(precision_score(y_test, y_pred, zero_division=0)),
        "recall": float(recall_score(y_test, y_pred, zero_division=0)),
        "f1": float(f1_score(y_test, y_pred, zero_division=0)),
        "roc_auc": roc_auc,
        "average_precision": avg_precision,
        "threshold_search": {
            "min": 0.01,
            "max": 0.50,
            "step": 0.01,
            "n_thresholds": len(threshold_values),
        },
        "threshold_tuning": threshold_results,
        "confusion_matrix": confusion_matrix(y_test, y_pred).tolist(),
        "classification_report": classification_report(
            y_test,
            y_pred,
            output_dict=True,
            zero_division=0,
        ),
        "behavior_checks": _build_behavior_check_report(
            deadlock_case_prob=behavior_probs["deadlock_case"],
            safe_case_prob=behavior_probs["safe_case"],
            threshold=best_threshold,
        ),
    }

    if logical_deadlock_rule is not None:
        valid_rule_mask = logical_deadlock_rule.notna()

        if bool(valid_rule_mask.any()):
            rule_series = logical_deadlock_rule.loc[valid_rule_mask].astype(int)
            pred_series = pd.Series(y_pred, index=y_test.index)
            pred_vs_rule = pred_series.loc[rule_series.index].astype(int)
            true_vs_rule = y_test.loc[rule_series.index].astype(int)

            mismatch_mask = pred_vs_rule != rule_series
            mismatch_indices = list(rule_series.index[mismatch_mask])

            mismatch_examples = []
            for mismatch_index in mismatch_indices[:10]:
                mismatch_examples.append(
                    {
                        "row_index": str(mismatch_index),
                        "model_prediction": int(pred_vs_rule.loc[mismatch_index]),
                        "logical_deadlock_rule": int(rule_series.loc[mismatch_index]),
                        "true_label": int(true_vs_rule.loc[mismatch_index]),
                    }
                )

            metrics["logic_alignment"] = {
                "enabled": True,
                "compared_rows": int(valid_rule_mask.sum()),
                "mismatch_count": int(np.sum(mismatch_mask)),
                "mismatch_ratio": float(np.mean(mismatch_mask)),
                "model_vs_rule_confusion_matrix": confusion_matrix(
                    rule_series,
                    pred_vs_rule,
                ).tolist(),
                "mismatch_examples": mismatch_examples,
            }
        else:
            metrics["logic_alignment"] = {
                "enabled": False,
                "reason": "No rows had a valid logical deadlock rule for comparison.",
            }
    else:
        metrics["logic_alignment"] = {
            "enabled": False,
            "reason": "Logical deadlock rule was not provided to evaluator.",
        }

    return metrics


def main() -> None:
    """Run full training workflow and save model/metrics artifacts."""
    # Parse script arguments.
    args = parse_args()

    # Ensure output directories exist.
    args.model_out.parent.mkdir(parents=True, exist_ok=True)
    args.metrics_out.parent.mkdir(parents=True, exist_ok=True)

    if args.train_mode == "matrix_synthetic":
        x_df, y_series, synthetic_info = generate_matrix_synthetic_dataset(
            n_samples=args.synthetic_samples,
            random_state=args.random_state,
            min_processes=args.synthetic_min_processes,
            max_processes=args.synthetic_max_processes,
            min_resources=args.synthetic_min_resources,
            max_resources=args.synthetic_max_resources,
        )
        group_from_column = False
        logical_deadlock_rule = y_series.astype(float).copy()
        feasibility_feature_info = {
            "enabled": True,
            "source": "matrix_synthetic_generation",
            "features_added": [],
            "valid_rows": int(len(x_df)),
            "invalid_rows": 0,
            "coverage_ratio": 1.0,
            "synthetic_info": synthetic_info,
        }
    else:
        # Load cleaned dataset.
        x_df, y_series, group_from_column = load_dataset(
            args.input,
            args.target,
            args.group_column,
        )

        # Add feasibility-aware features from matrix state when matrix columns are available.
        x_df, logical_deadlock_rule, feasibility_feature_info = add_feasibility_features(x_df)

    # Capture first target values before shuffle for debugging ordering bias.
    target_head_before_shuffle = y_series.head(10).tolist()

    # Shuffle rows ONCE in-memory before any group creation or splitting.
    shuffled_index = x_df.sample(frac=1.0, random_state=args.random_state).index
    x_df = x_df.loc[shuffled_index].reset_index(drop=True)
    y_series = y_series.loc[shuffled_index].reset_index(drop=True)
    logical_deadlock_rule = logical_deadlock_rule.loc[shuffled_index].reset_index(drop=True)

    # Capture first target values after shuffle to confirm shuffling happened.
    target_head_after_shuffle = y_series.head(10).tolist()

    # Build groups AFTER shuffle to avoid ordering bias in grouping/splitting.
    if args.group_column in x_df.columns:
        groups = x_df[args.group_column].astype(str).copy()
        x_df = x_df.drop(columns=[args.group_column]).copy()
    else:
        groups = build_pattern_keys(x_df)

    # Full-dataset class distribution for debugging and monitoring.
    full_class_distribution = summarize_class_distribution(y_series)

    # Split dataset according to chosen strategy.
    x_train, x_test, y_train, y_test, split_info = split_dataset(
        x_df=x_df,
        y_series=y_series,
        groups=groups,
        test_size=args.test_size,
        random_state=args.random_state,
        split_mode=args.split_mode,
    )

    # Compute leakage-focused diagnostics for this exact split.
    leakage_diagnostics = compute_leakage_diagnostics(
        x_df=x_df,
        y_series=y_series,
        train_groups=split_info["group_train"],
        test_groups=split_info["group_test"],
    )

    # Train/test class distributions for split-quality diagnostics.
    train_class_distribution = summarize_class_distribution(y_train)
    test_class_distribution = summarize_class_distribution(y_test)

    # Build and train the model pipeline.
    pipeline = build_training_pipeline(x_df, random_state=args.random_state)
    pipeline.fit(x_train, y_train)

    # Evaluate model on holdout set.
    logical_deadlock_test = logical_deadlock_rule.loc[x_test.index]
    metrics = evaluate_model(
        pipeline,
        x_test,
        y_test,
        logical_deadlock_rule=logical_deadlock_test,
    )

    # Add simple metadata to metrics output for traceability.
    metrics["metadata"] = {
        "input_dataset": str(args.input),
        "target": args.target,
        "n_rows": int(len(x_df)),
        "n_features": int(x_df.shape[1]),
        "train_rows": int(len(x_train)),
        "test_rows": int(len(x_test)),
        "feature_columns": x_df.columns.tolist(),
        "random_state": int(args.random_state),
        "test_size": float(args.test_size),
        "dataset_shuffled_once": True,
        "target_head_before_shuffle": target_head_before_shuffle,
        "target_head_after_shuffle": target_head_after_shuffle,
        "class_distribution": {
            "full": full_class_distribution,
            "train": train_class_distribution,
            "test": test_class_distribution,
        },
        "split_mode": split_info.get("split_mode", args.split_mode),
        "split_info": {
            key: value
            for key, value in split_info.items()
            if key not in {"group_train", "group_test"}
        },
        "group_column": args.group_column,
        "group_column_found_in_input": bool(group_from_column),
        "train_mode": args.train_mode,
        "feasibility_features": feasibility_feature_info,
        "model": "LogisticRegression",
    }
    metrics["leakage_diagnostics"] = leakage_diagnostics

    # Save model artifact with pipeline and metadata in a single file.
    model_artifact = {
        "pipeline": pipeline,
        "feature_columns": x_df.columns.tolist(),
        "target_column": args.target,
        "decision_threshold": metrics["best_threshold"],
    }
    joblib.dump(model_artifact, args.model_out)

    # Save metrics report as JSON.
    with args.metrics_out.open("w", encoding="utf-8") as metrics_file:
        json.dump(metrics, metrics_file, indent=2)

    # Print concise run summary for quick terminal feedback.
    print("Training complete")
    print(f"Input: {args.input}")
    print(f"Model saved to: {args.model_out}")
    print(f"Metrics saved to: {args.metrics_out}")
    print("Dataset shuffled once before grouping/splitting: True")
    print(f"Target head before shuffle: {target_head_before_shuffle}")
    print(f"Target head after shuffle:  {target_head_after_shuffle}")
    print(f"Class distribution (full):  {full_class_distribution}")
    print(f"Class distribution (train): {train_class_distribution}")
    print(f"Class distribution (test):  {test_class_distribution}")
    print(f"Best threshold (max F1): {metrics['best_threshold']:.2f}")
    print(f"Accuracy: {metrics['accuracy']:.4f}")
    print(f"Precision: {metrics['precision']:.4f}")
    print(f"Recall: {metrics['recall']:.4f}")
    print(f"F1: {metrics['f1']:.4f}")
    if metrics["roc_auc"] is None:
        print("ROC-AUC: not defined (single-class test set)")
    else:
        print(f"ROC-AUC: {metrics['roc_auc']:.4f}")
    print(f"Split mode used: {metrics['metadata']['split_mode']}")
    print(
        "Test pattern overlap ratio: "
        f"{metrics['leakage_diagnostics']['test_pattern_overlap_ratio']:.4f}"
    )
    if metrics["logic_alignment"].get("enabled", False):
        print(
            "Model vs feasibility-rule mismatch ratio: "
            f"{metrics['logic_alignment']['mismatch_ratio']:.4f} "
            f"({metrics['logic_alignment']['mismatch_count']}/"
            f"{metrics['logic_alignment']['compared_rows']})"
        )
        if metrics["logic_alignment"]["mismatch_examples"]:
            print(
                "First mismatch example: "
                f"{metrics['logic_alignment']['mismatch_examples'][0]}"
            )
    else:
        print(
            "Model vs feasibility-rule comparison skipped: "
            f"{metrics['logic_alignment'].get('reason', 'n/a')}"
        )
    if metrics["behavior_checks"]["passes_all"]:
        print("Behavior checks passed for canonical deadlock/safe cases")
    else:
        print("Behavior check mismatches detected:")
        for mismatch in metrics["behavior_checks"]["mismatches"]:
            print(f"- {mismatch}")


# Script entry point.
if __name__ == "__main__":
    main()
